// ~/.mozilla/firefox/<profile>/user.js
//
// Privacy and security settings are handled by policies in /etc/firefox/policies/policies.json
// This user.js consists mostly of specific browser behaviour and UI configurations, with only a
// handfull of additional privacy and security tweaks.
//
// Last revised: 2025-12-01 (FF 145.0.2)
//
//
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.enabled", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("browser.aboutwelcome.enabled", false);
user_pref("browser.aboutwelcome.screens", "");
user_pref("browser.bookmarks.defaultLocation", "menu");
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.contentblocking.report.show_mobile_app", false);
user_pref("browser.download.always_ask_before_handling_new_types", false);
user_pref("browser.download.autohideButton", false);
user_pref("browser.messaging-system.whatsNewPanel.enabled", false);
user_pref("browser.newtabpage.activity-stream.showWeather", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.preferences.moreFromMozilla", false);
user_pref("browser.privatebrowsing.forceMediaMemoryCache", true);
user_pref("browser.privatebrowsing.resetPBM.enabled", true);
user_pref("browser.profiles.group.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "");
user_pref("browser.sessionstore.privacy_level", 2);
user_pref("browser.startup.firstrunSkipsHomepage", true);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.startup.homepage_override.buildID", "");
user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.tabs.firefox-view", false);
user_pref("browser.tabs.tabmanager.enabled", false);
user_pref("browser.theme.content-theme", 0);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.translations.automaticallyPopup", false);
user_pref("browser.translations.enable", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"nordpassstandalone_nordsecurity_com-browser-action\",\"_446900e4-71c2-419f-a6a7-df9c091e268b_-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"bookmarks-menu-button\",\"downloads-button\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\",\"ublock0_raymondhill_net-browser-action\",\"reset-pbm-toolbar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"ublock0_raymondhill_net-browser-action\",\"nordpassstandalone_nordsecurity_com-browser-action\",\"_446900e4-71c2-419f-a6a7-df9c091e268b_-browser-action\",\"reset-pbm-toolbar-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\",\"PersonalToolbar\",\"unified-extensions-area\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":21,\"newElementCount\":3}");
user_pref("browser.uidensity", 1);
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.shortcuts.bookmarks", false);
user_pref("browser.urlbar.shortcuts.history", false);
user_pref("browser.urlbar.shortcuts.tabs", false);
user_pref("browser.urlbar.suggest.bookmark", false);
user_pref("browser.urlbar.suggest.clipboard", false);
user_pref("browser.urlbar.suggest.engines", false);
user_pref("browser.urlbar.suggest.history", false);
user_pref("browser.urlbar.suggest.openpage", false);
user_pref("browser.urlbar.suggest.pocket", false);
user_pref("browser.urlbar.suggest.quickactions", false);
user_pref("browser.urlbar.suggest.recentsearches", false);
user_pref("browser.urlbar.suggest.remotetab", false);
user_pref("browser.urlbar.suggest.searches", false);
user_pref("browser.urlbar.suggest.topsites", false);
user_pref("browser.urlbar.suggest.trending", false);
user_pref("browser.urlbar.suggest.weather", false);
user_pref("cookiebanners.bannerClicking.enabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.usage.uploadEnabled", false);
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("geo.provider.use_geoclue", false);
user_pref("geo.provider.use_gpsd", false);
user_pref("geo.wifi.uri", "");
user_pref("layout.css.prefers-color-scheme.content-override", 0);
user_pref("layout.spellcheckDefault", 0);
user_pref("media.gmp-gmpopenh264.enabled", true);
user_pref("media.hardwaremediakeys.enabled", false);
user_pref("media.peerconnection.enabled", false);
user_pref("network.http.sendRefererHeader", 0);
user_pref("network.IDN_show_punycode", true);
user_pref("network.manage-offline-status", false);
user_pref("places.history.enabled", false);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.firstparty.isolate", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", 0);
user_pref("privacy.query_stripping.enabled.pbmode", true);
user_pref("privacy.query_stripping.enabled", true);
user_pref("security.pki.crlite_mode", 2);
user_pref("security.sandbox.content.level", 4);
user_pref("security.tls.version.min", 3);
user_pref("signon.autofillForms", false);
user_pref("signon.firefoxRelay.feature", "disabled");
user_pref("signon.generation.enabled", false);
user_pref("signon.management.page.breach-alerts.enabled", false);
user_pref("signon.privateBrowsingCapture.enabled", false);
user_pref("signon.rememberSignons", false);
user_pref("toolkit.telemetry.previousBuildID", "");
user_pref("webgl.disabled", true);
user_pref("zoom.minPercent", 110);
